# Generated by Django 4.2.6 on 2023-10-27 23:19



from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
